website_mappings = {
    "google": "https://google.com",
    "reddit": "https://reddit.com",
    "discord": "https://discord.com",
    "youtube": "https://youtube.com",
    "chatgpt": "https://chat.openai.com",
    "whatsapp": "https://web.whatsapp.com",
    "facebook": "https://facebook.com",
    "instagram": "https://instagram.com",
    "vscode": "https://code.visualstudio.com",
    "visual studio code": "https://code.visualstudio.com",
    "visual studio": "https://visualstudio.microsoft.com",
    "vs": "https://visualstudio.microsoft.com",
    "twitter": "https://twitter.com",
    "x": "https://x.com",
    "chess": "https://chess.com",
    "github": "https://github.com",
    "gmail": "https://gmail.com",
    "yahoo": "https://yahoo.com",
    "replit": "https://replit.com",
    "google translate": "https://translate.google.com",
    "google classroom": "https://classroom.google.com",
    "google meets": "https://meets.google.com",
    "google meet": "https://meets.google.com",
    "node js": "https://nodejs.org",
    "node": "https://node.js.org",
    "amazon": "https://amazon.com",
    "amazon web services": "https://aws.com",
    "aws": "https://aws.com",
    "amazon web": "https://aws.com",
    "amazon services": "https://aws.com",
    "web services": "https://aws.com",
    "amazon service": "https://aws.com",
    "web service": "https://aws.com",
    "threads": "https://threads.com",
    "stripe": "https://stripe.com",
    "wikipedia": "https://wikipedia.org",
    "android studio": "https://developer.android.com/studio",
    "android developers": "https://developer.android.com/studio",
    "android developer": "https://developer.android.com/studio",
    "android": "https://developer.android.com/studio",
    "twitch": "https://twitch.tv",
    "twitch tv": "https://twitch.tv",
    "chessly": "https://chessly.com",
    "vimeo": "https://vimeo.com",
    "viber": "https://viber.com",
    "paypal": "https://paypal.com",
    "cash app": "https://cashapp.com",
    "cashapp": "https://cashapp.com",
    "zelle": "https://zellepay.com",
    "zelle pay": "https://zellepay.com",
    "zellepay": "https://zellepay.com",
    "maps": "https://maps.google.com",
    "google maps": "https://maps.google.com",
    "apple": "https://apple.com",
    "apple store": "https://apple.com",
    "finance": "https://finance.google.com",
    "google finance": "https://finance.google.com",
    "zoom": "https://zoom.com",
    "zoom meeting": "https://zoom.com",
    "zoom meetings": "https://zoom.com",
    "play store": "https://play.google.com",
    "google play": "https://play.google.com",
    "google play store": "https://play.google.com",
    "app store": "https://apps.apple.com",
    "apple app store": "https://apps.apple.com",
    "apple store": "https://apps.apple.com",
    "apple app": "https://apps.apple.com",
    "apple apps": "https://apps.apple.com",
    "bard": "https://bard.google.com",
    "google bard": "https://bard.google.com",
    "google bard ai": "https://bard.google.com",
    "bard experimental": "https://bard.google.com",
    "bard ai": "https://bard.google.com",
    "bard experimental ai": "https://bard.google.com",
    "lichess": "https://lichess.org",
    "quora": "https://quora.com",
    "rotten tomatoes": "https://rottentomatoes.com",
    "mbc": "https://mbc.net",
    "mbc.net": "https://mbc.net",
    "shahid": "https://shahid.mbc.net",
    "shahid.net": "https://shahid.mbc.net",
    "skynet": "https://skynet.com",
    "flutter": "https://flutter.dev",
    "flutter.dev": "https://flutter.dev",
    "flutter framework": "https://flutter.dev",
    "apple": "https://www.apple.com",
    "microsoft": "https://www.microsoft.com",
    "amazon.com": "https://www.amazon.com",
    "google": "https://www.google.com",
    "facebook": "https://www.facebook.com",
    "tesla": "https://www.tesla.com",
    "ibm": "https://www.ibm.com",
    "walmart": "https://www.walmart.com",
    "coca-cola company": "https://www.coca-cola.com",
    "toyota motor": "https://www.toyota.com",
    "samsung electronics": "https://www.samsung.com",
    "intel": "https://www.intel.com",
    "johnson & johnson": "https://www.jnj.com",
    "procter & gamble": "https://www.pg.com",
    "general electric company": "https://www.ge.com",
    "verizon communications": "https://www.verizon.com",
    "at&t": "https://www.att.com",
    "pfizer": "https://www.pfizer.com",
    "netflix": "https://www.netflix.com",
    "adobe": "https://www.adobe.com",
    "mcdonald's": "https://www.mcdonalds.com",
    "visa": "https://www.visa.com",
    "mastercard incorporated": "https://www.mastercard.com",
    "the boeing company": "https://www.boeing.com",
    "nvidia": "https://www.nvidia.com",
    "oracle": "https://www.oracle.com",
    "salesforce.com": "https://www.salesforce.com",
    "cisco systems": "https://www.cisco.com",
    "walt disney company": "https://www.disney.com",
    "bmw group": "https://www.bmw.com",
    "general motors company": "https://www.gm.com",
    "pepsico": "https://www.pepsico.com",
    "sony": "https://www.sony.com",
    "exxon mobil": "https://www.exxonmobil.com",
    "the home depot": "https://www.homedepot.com",
    "starbucks": "https://www.starbucks.com",
    "ibm": "https://www.ibm.com",
    "target": "https://www.target.com",
    "american express company": "https://www.americanexpress.com",
    "the coca-cola company": "https://www.coca-cola.com",
    "nike": "https://www.nike.com",
    "adobe systems incorporated": "https://www.adobe.com",
    "twitter": "https://www.twitter.com",
    "intel": "https://www.intel.com",
    "linkedin": "https://www.linkedin.com",
    "ford motor company": "https://www.ford.com",
    "general electric": "https://www.ge.com",
    "visa": "https://www.visa.com",
    "johnson & johnson": "https://www.jnj.com",
    "procter & gamble company": "https://www.pg.com",
    "the home depot": "https://www.homedepot.com",
    "verizon communications": "https://www.verizon.com",
    "at&t": "https://www.att.com",
    "amazon web services": "https://aws.amazon.com",
    "uber technologies": "https://www.uber.com",
    "airbnb": "https://www.airbnb.com",
    "paypal holdings": "https://www.paypal.com",
    "walmart stores": "https://www.walmart.com",
    "intel": "https://www.intel.com",
    "tesla motors": "https://www.tesla.com",
    "the boeing company": "https://www.boeing.com",
    "general motors": "https://www.gm.com",
    "oracle": "https://www.oracle.com",
    "facebook": "https://www.facebook.com",
    "alphabet": "https://www.abc.xyz",
    "microsoft": "https://www.microsoft.com",
    "the coca-cola company": "https://www.coca-cola.com",
    "pepsico": "https://www.pepsico.com",
    "nike": "https://www.nike.com",
    "walt disney": "https://www.disney.com",
    "starbucks": "https://www.starbucks.com",
    "ibm": "https://www.ibm.com",
    "mcdonald's": "https://www.mcdonalds.com",
    "visa": "https://www.visa.com",
    "mastercard incorporated": "https://www.mastercard.com",
    "american express company": "https://www.americanexpress.com",
    "johnson & johnson": "https://www.jnj.com",
    "procter & gamble": "https://www.pg.com",
    "the home depot": "https://www.homedepot.com",
    "verizon communications": "https://www.verizon.com",
    "at&t": "https://www.att.com",
    "exxon mobil": "https://www.exxonmobil.com",
    "chevron": "https://www.chevron.com",
    "bp plc": "https://www.bp.com",
    "royal dutch shell plc": "https://www.shell.com",
    "tesla": "https://www.tesla.com",
    "toyota motor": "https://www.toyota.com",
    "general electric company": "https://www.ge.com",
    "siemens ag": "https://www.siemens.com",
    "samsung electronics": "https://www.samsung.com",
    "apple": "https://www.apple.com",
    "microsoft": "https://www.microsoft.com",
    "amazon.com": "https://www.amazon.com",
    "google": "https://www.google.com",
    "facebook": "https://www.facebook.com",
    "twitter": "https://www.twitter.com",
    "intel": "https://www.intel.com",
    "ibm": "https://www.ibm.com",
    "oracle": "https://www.oracle.com",
    "salesforce.com": "https://www.salesforce.com",
    "cisco systems": "https://www.cisco.com",
    "adobe": "https://www.adobe.com",
    "nvidia": "https://www.nvidia.com",
    "netflix": "https://www.netflix.com",
    "spotify technology s.a.": "https://www.spotify.com",
    "uber technologies": "https://www.uber.com",
    "airbnb": "https://www.airbnb.com",
    "paypal holdings": "https://www.paypal.com",
    "walmart": "https://www.walmart.com",
    "target": "https://www.target.com",
    "best buy": "https://www.bestbuy.com",
    "costco wholesale": "https://www.costco.com",
    "alibaba group holding limited": "https://www.alibaba.com",
    "tencent holdings limited": "https://www.tencent.com",
    "sony": "https://www.sony.com",
    "lg electronics": "https://www.lg.com",
    "samsung electronics": "https://www.samsung.com",
    "panasonic": "https://www.panasonic.com",
    "lenovo group limited": "https://www.lenovo.com",
    "huawei technologies": "https://www.huawei.com",
    "xiaomi": "https://www.mi.com",
    "the coca-cola company": "https://www.coca-cola.com",
    "pepsico": "https://www.pepsico.com",
    "nestlé s.a.": "https://www.nestle.com",
    "kraft heinz company": "https://www.kraftheinz.com",
    "mondelez international": "https://www.mondelezinternational.com",
    "unilever": "https://www.unilever.com",
    "the procter & gamble company": "https://www.pg.com",
    "johnson & johnson": "https://www.jnj.com",
    "colgate-palmolive company": "https://www.colgate.com",
    "the estée lauder companies": "https://www.elcompanies.com",
    "l'oréal s.a.": "https://www.loreal.com",
    "danone s.a.": "https://www.danone.com",
    "kellogg company": "https://www.kelloggs.com",
    "general mills": "https://www.generalmills.com",
    "campbell soup company": "https://www.campbells.com",
    "the hershey company": "https://www.hersheys.com",
    "amazon web services": "https://aws.amazon.com",
    "microsoft azure": "https://azure.microsoft.com",
    "google cloud platform": "https://cloud.google.com",
    "ibm cloud": "https://www.ibm.com/cloud",
    "adobe creative cloud": "https://www.adobe.com/creativecloud.html",
    "salesforce.com": "https://www.salesforce.com",
    "oracle cloud": "https://www.oracle.com/cloud",
    "dropbox": "https://www.dropbox.com",
    "box": "https://www.box.com",
    "slack technologies": "https://www.slack.com",
    "zoom video communications": "https://www.zoom.us",
    "cisco webex": "https://www.webex.com",
    "microsoft teams": "https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software",
    "trello": "https://www.trello.com",
    "asana": "https://www.asana.com",
    "monday.com": "https://www.monday.com",
    "walmart stores": "https://www.walmart.com",
    "target": "https://www.target.com",
    "macy's": "https://www.macys.com",
    "kohl's": "https://www.kohls.com",
    "nordstrom": "https://www.nordstrom.com",
    "amazon go": "https://www.amazon.com/go",
    "apple retail stores": "https://www.apple.com/retail",
    "best buy": "https://www.bestbuy.com",
    "alibaba group holding limited": "https://www.alibaba.com",
    "ebay": "https://www.ebay.com",
    "jd.com": "https://www.jd.com",
    "rakuten": "https://www.rakuten.com",
    "shopify": "https://www.shopify.com",
    "magento commerce": "https://magento.com",
    "wix.com": "https://www.wix.com",
    "squarespace": "https://www.squarespace.com",
    "wordpress.com": "https://wordpress.com",
    "medium": "https://www.medium.com",
    "tumblr": "https://www.tumblr.com",
    "linkedin": "https://www.linkedin.com",
    "glassdoor": "https://www.glassdoor.com",
    "indeed": "https://www.indeed.com",
    "monster worldwide": "https://www.monster.com",
    "ziprecruiter": "https://www.ziprecruiter.com",
    "upwork global": "https://www.upwork.com",
    "fiverr international": "https://www.fiverr.com",
    "freelancer.com": "https://www.freelancer.com",
    "uber technologies": "https://www.uber.com",
    "lyft": "https://www.lyft.com",
    "grab holdings": "https://www.grab.com",
    "didi chuxing technology": "https://www.didiglobal.com",
    "ola cabs": "https://www.olacabs.com",
    "gojek tech": "https://www.gojek.com",
    "airbnb": "https://www.airbnb.com",
    "booking holdings": "https://www.bookingholdings.com",
    "expedia group": "https://www.expediagroup.com",
    "tripadvisor": "https://www.tripadvisor.com",
    "agoda company pte.": "https://www.agoda.com",
    "trivago": "https://www.trivago.com",
    "kayak software": "https://www.kayak.com",
    "skyscanner": "https://www.skyscanner.com",
    "travelocity": "https://www.travelocity.com",
    "orbitz worldwide": "https://www.orbitz.com",
    "priceline.com": "https://www.priceline.com",
    "hotwire": "https://www.hotwire.com",
    "hotels.com": "https://www.hotels.com",
    "homeaway": "https://www.homeaway.com",
    "vrbo": "https://www.vrbo.com",
    "zillow group": "https://www.zillow.com",
    "redfin": "https://www.redfin.com",
    "realtor.com": "https://www.realtor.com",
    "trulia": "https://www.trulia.com",
    "compass": "https://www.compass.com",
    "opendoor technologies": "https://www.opendoor.com",
    "knock": "https://www.knock.com",
    "offerpad solutions": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "red ventures": "https://www.redventures.com",
    "iac/interactivecorp": "https://www.iac.com",
    "expedia group": "https://www.expedia.com",
    "tripadvisor": "https://www.tripadvisor.com",
    "hotels.com": "https://www.hotels.com",
    "booking.com b.v.": "https://www.booking.com",
    "agoda company pte.": "https://www.agoda.com",
    "kayak software": "https://www.kayak.com",
    "trivago": "https://www.trivago.com",
    "hotwire": "https://www.hotwire.com",
    "orbitz worldwide": "https://www.orbitz.com",
    "travelocity": "https://www.travelocity.com",
    "priceline.com": "https://www.priceline.com",
    "homeaway": "https://www.homeaway.com",
    "vrbo": "https://www.vrbo.com",
    "zillow group": "https://www.zillow.com",
    "redfin": "https://www.redfin.com",
    "realtor.com": "https://www.realtor.com",
    "trulia": "https://www.trulia.com",
    "compass": "https://www.compass.com",
    "opendoor technologies": "https://www.opendoor.com",
    "offerpad solutions": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "open listings": "https://www.openlistings.com",
    "properties online": "https://www.propertiesonline.com",
    "forsalebyowner.com": "https://www.forsalebyowner.com",
    "fsbo.com": "https://www.fsbo.com",
    "homefinder.com": "https://www.homefinder.com",
    "homes.com": "https://www.homes.com",
    "houzz": "https://www.houzz.com",
    "remax": "https://www.remax.com",
    "keller williams realty": "https://www.kw.com",
    "coldwell banker real estate": "https://www.coldwellbanker.com",
    "century 21 real estate": "https://www.century21.com",
    "sotheby's international realty": "https://www.sothebysrealty.com",
    "corcoran group": "https://www.corcoran.com",
    "elliman.com": "https://www.elliman.com",
    "redfin": "https://www.redfin.com",
    "compass": "https://www.compass.com",
    "opendoor technologies": "https://www.opendoor.com",
    "zillow group": "https://www.zillow.com",
    "offerpad solutions": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "oakland real estate": "https://www.oaklandrealestate.com",
    "property brothers": "https://www.propertybrothers.com",
    "kw.com": "https://www.kw.com",
    "raveis.com": "https://www.raveis.com",
    "rethink council": "https://www.rethinkcouncil.com",
    "elad group": "https://www.eladgroup.com",
    "bhhsnyproperties.com": "https://www.bhhsnyproperties.com",
    "corcoran.com": "https://www.corcoran.com",
    "halstead.com": "https://www.halstead.com",
    "bhsusa.com": "https://www.bhsusa.com",
    "westside1.com": "https://www.westside1.com",
    "eastcoast1.com": "https://www.eastcoast1.com",
    "upstate1.com": "https://www.upstate1.com",
    "manhattan1.com": "https://www.manhattan1.com",
    "brooklyn1.com": "https://www.brooklyn1.com",
    "corcoran.com": "https://www.corcoran.com",
    "theagencyre.com": "https://www.theagencyre.com",
    "elliman.com": "https://www.elliman.com",
    "zillow.com": "https://www.zillow.com",
    "redfin.com": "https://www.redfin.com",
    "compass.com": "https://www.compass.com",
    "trulia.com": "https://www.trulia.com",
    "remax.com": "https://www.remax.com",
    "coldwellbanker.com": "https://www.coldwellbanker.com",
    "century21.com": "https://www.century21.com",
    "sothebysrealty.com": "https://www.sothebysrealty.com",
    "zillow.com": "https://www.zillow.com",
    "kw.com": "https://www.kw.com",
    "raveis.com": "https://www.raveis.com",
    "rethinkcouncil.com": "https://www.rethinkcouncil.com",
    "elliman.com": "https://www.elliman.com",
    "zillow.com": "https://www.zillow.com",
    "redfin.com": "https://www.redfin.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offferpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "zillow.com": "https://www.zillow.com",
    "redfin.com": "https://www.redfin.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offferpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "openlistings.com": "https://www.openlistings.com",
    "zillow.com": "https://www.zillow.com",
    "redfin.com": "https://www.redfin.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offerpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "zillow.com": "https://www.zillow.com",
    "redfin.com": "https://www.redfin.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offerpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "propertiesonline.com": "https://www.propertiesonline.com",
    "forsalebyowner.com": "https://www.forsalebyowner.com",
    "fsbo.com": "https://www.fsbo.com",
    "homefinder.com": "https://www.homefinder.com",
    "homes.com": "https://www.homes.com",
    "houzz.com": "https://www.houzz.com",
    "remax.com": "https://www.remax.com",
    "kw.com": "https://www.kw.com",
    "coldwellbanker.com": "https://www.coldwellbanker.com",
    "century21.com": "https://www.century21.com",
    "sothebysrealty.com": "https://www.sothebysrealty.com",
    "zillow.com": "https://www.zillow.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offerpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "openlistings.com": "https://www.openlistings.com",
    "propertiesonline.com": "https://www.propertiesonline.com",
    "forsalebyowner.com": "https://www.forsalebyowner.com",
    "fsbo.com": "https://www.fsbo.com",
    "homefinder.com": "https://www.homefinder.com",
    "homes.com": "https://www.homes.com",
    "houzz.com": "https://www.houzz.com",
    "remax.com": "https://www.remax.com",
    "kw.com": "https://www.kw.com",
    "coldwellbanker.com": "https://www.coldwellbanker.com",
    "century21.com": "https://www.century21.com",
    "sothebysrealty.com": "https://www.sothebysrealty.com",
    "zillow.com": "https://www.zillow.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offerpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "propertiesonline.com": "https://www.propertiesonline.com",
    "forsalebyowner.com": "https://www.forsalebyowner.com",
    "fsbo.com": "https://www.fsbo.com",
    "homefinder.com": "https://www.homefinder.com",
    "homes.com": "https://www.homes.com",
    "houzz.com": "https://www.houzz.com",
    "remax.com": "https://www.remax.com",
    "kw.com": "https://www.kw.com",
    "coldwellbanker.com": "https://www.coldwellbanker.com",
    "century21.com": "https://www.century21.com",
    "sothebysrealty.com": "https://www.sothebysrealty.com",
    "zillow.com": "https://www.zillow.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offerpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "openlistings.com": "https://www.openlistings.com",
    "zillow.com": "https://www.zillow.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offerpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com",
    "openlistings.com": "https://www.openlistings.com",
    "propertiesonline.com": "https://www.propertiesonline.com",
    "forsalebyowner.com": "https://www.forsalebyowner.com",
    "fsbo.com": "https://www.fsbo.com",
    "homefinder.com": "https://www.homefinder.com",
    "homes.com": "https://www.homes.com",
    "houzz.com": "https://www.houzz.com",
    "remax.com": "https://www.remax.com",
    "kw.com": "https://www.kw.com",
    "coldwellbanker.com": "https://www.coldwellbanker.com",
    "century21.com": "https://www.century21.com",
    "sothebysrealty.com": "https://www.sothebysrealty.com",
    "zillow.com": "https://www.zillow.com",
    "compass.com": "https://www.compass.com",
    "opendoor.com": "https://www.opendoor.com",
    "offerpad.com": "https://www.offerpad.com",
    "ibuyer.com": "https://www.ibuyer.com"
}
